{% set version = "0.0.0.2" %}

package:
  name: etcdpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/etcdpy/etcdpy-{{ version }}.tar.gz
  sha256: a3e46e2b117547839c6d2c1ece3b6d3c1a66dc2cfb64f1dac41b1599b54af3ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - grpcio >=1.51.1
    - protobuf >=4.21.12

test:
  imports:
    - etcd3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/candango/etcdpy
  summary: Python client for etcd
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
